/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package util;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.sql.DataSource;
import modelos.Formularios;
import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.ResultSetHandler;
import org.apache.commons.dbutils.handlers.BeanListHandler;


/**
 *
 * @author Flavio
 */
public class ConectaMeu {
    
    public static void main(String[] args) throws SQLException {
     
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        Connection connection;
        Conexao conf = new Conexao();
        String query = "";
        Statement st;
        ResultSet rs;

        List<Formularios> listatudo;

        connection = conf.getDatabaseConnection();

        QueryRunner run = new QueryRunner((DataSource) connection);
        ResultSetHandler<List<Formularios>> h = new BeanListHandler<>(Formularios.class);

        // Execte the SQL statement and return the results in a List of
        // Person objects generated by the BeanListHandler.
        List<Formularios> persons = run.query("SELECT * FROM freebits_13.formularios", h);
        
        System.out.println(persons);
        
      
       
        
    }
    
   
}
        
        
        
    
    
    
    
    
    
    
